from flask import Flask, render_template, request, flash

app = Flask(__name__)
app.secret_key="hello"

@app.route("/",methods=["GET", "POST"])
def form():
    data = []
    if request.method=="POST":
        data.append(int(request.form['client_id']))
        data.append(request.form['clerk_type'])
        data.append(request.form['pay_day'])
        data.append(request.form['submition_type'])
        data.append(request.form['additional_cards'])
        data.append(request.form['postal_address_type'])
        data.append(request.form['sex'])
        data.append(request.form['marital_status'])
        data.append(request.form['quant_depend'])
        data.append(request.form['edu_level'])
        data.append(request.form['birth_state'])
        data.append(request.form['birth_city'])
        data.append(request.form['nationality'])
        data.append(request.form['residential_state'])
        data.append(request.form['residential_city'])
        data.append(request.form['residential_borough'])
        data.append(request.form['res_phone'])
        data.append(request.form['res_phone_area'])
        data.append(request.form['res_type'])
        data.append(request.form['months_in_res'])
        data.append(request.form['phone'])
        data.append(request.form['email'])
        data.append(request.form['per_month_income'])
        data.append(request.form['other_income'])
        data.append(request.form['visa'])
        data.append(request.form['master'])
        data.append(request.form['diners'])
        data.append(request.form['am'])
        data.append(request.form['other_cards'])
        data.append(request.form['num_bank_acc'])
        data.append(request.form['num_special_bank_acc'])
        data.append(request.form['per_asssets_value'])
        data.append(request.form['num_cars'])
        data.append(request.form['company'])
        data.append(request.form['prof_state'])
        data.append(request.form['prof_city'])
        data.append(request.form['prof_borough'])
        data.append(request.form['prof_phone'])
        data.append(request.form['prof_phone_area'])
        data.append(request.form['job_month'])
        data.append(request.form['prof_code'])
        data.append(request.form['occupation'])
        data.append(request.form['mate_prof'])
        data.append(request.form['mate_edu_level'])
        data.append(request.form['address'])
        data.append(request.form['rg'])
        data.append(request.form['cpf'])
        data.append(request.form['income'])
        data.append(request.form['product'])
        data.append(request.form['acsp'])
        data.append(request.form['age'])
        data.append(request.form['res_zip_3'])
        data.append(request.form['prof_zip_3'])
        flash(f"The client's ID is {data[0]}")
    return render_template("index.html")

if __name__=="__main__":
    app.run(debug=True)