version: "3.8"

services:
  app:
    build:
      context: ./app
      target: build
    ports:
      - "8000:80"
    depends_on:
      - redis
      - model
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  model:
    build:
      context: ./models
      target: build
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: "redis:alpine"
